### ISSUE TITLE
R2DBC API: Expose product name

### ISSUE THREAD

**Issue by mp911de** [r2dbc/r2dbc-client#2]
`ConnectionFactory` should expose a product name, ideally as part of driver-metadata. Optionally, the metadata could also expose server-metadata.

The product name is a useful detail when configuring `SQLErrorCodeSQLExceptionTranslator`.

**Comment by nebhale** [comment]
What would you think this should look like?  Something like `Map<String, String> getMetadata()` or more specific `Metadata getMetadata()`?

**Comment by mp911de** [comment]
Let's stick with a `Metadata getMetadata()` to give value objects a meaningful name.

**Comment by nebhale** [comment]
Sounds good.  Pushed through with a static name on the PostgreSQL implementation.  I'd expect to extend both the interface and PostgreSQL class with new, strongly named and typed methods based on feedback.
