### ISSUE TITLE
How connection polling is handled internally

### ISSUE THREAD

**Issue by thekalinga** [r2dbc/r2dbc-client#27]
Couple of questions

1. Does the library do connection pooling internally, if so how to configure the pool
2. Can this be integrated with a connection pool library like Hikari?

**Comment by mp911de** [comment]
The answer to both questions is no. We do not have a connection pool yet. It would make sense to provide pooling to reuse connections.

Hikari is entirely based on JDBC. R2DBC is not compatible with JDBC, API-wise and conceptually as JDBC is a blocking API.

**Comment by thekalinga** [comment]
@mp911de Thanks for clarifying

**Comment by nebhale** [comment]
@thekalinga It's not on the roadmap for [M7](https://github.com/r2dbc/r2dbc-spi/milestone/4), but it is on our radar as something we'd like to have.  The plan is to allow Project Reactor to create a generic reactive pool and then make use of in once it is available.

**Comment by thekalinga** [comment]
@nebhale Thanks for clarifying

Is it something along the lines of [rxjava2-jdbc](https://github.com/davidmoten/rxjava2-jdbc)? (ofcourse it will not be tied to connection objects per se, but a generic enough object pool that someone can subscribe to & use the shared resource when available & relinquish it back to pool)

cc @simonbasle

**Comment by nebhale** [comment]
@thekalinga Yep, that's the plan.
