### ISSUE TITLE
Require subscription on write operations?

### ISSUE THREAD

**Issue by aguibert** [r2dbc/r2dbc-client#28]
In project reactor if you don't subscribe to a stream, nothing happens. This is fine if we are reading data, but is very un-intuitive if we are writing data to a database, where we typically don't care about any sort of feedback (unless an exception has been thrown).

Consider the following code example:
```java
R2dbc r2dbc = // ...
r2dbc.inTransaction(handle -> handle.execute("INSERT INTO test VALUES ($1)", 100));
```

With the above code, it looks like we are inserting some data into a table, but nothing goes into the DB until we subscribe to the writer operation in some way, such as:
```java
R2dbc r2dbc = // ...
r2dbc.inTransaction(handle -> handle.execute("INSERT INTO test VALUES ($1)", 100))
     .subscribe();
```

In JDBC we have two different operations for reads and writes (`Statement.executeQuery()` and `Statement.executeUpdate()` respectively), so perhaps we could do something similar in R2DBC?  The difference being that read operations still need to be subscribed to, but write operations do not require a subscription.

**Comment by gregturn** [comment]
We need a little more context. 

Where does this operation occur? If it was a Spring WebFlux POST, this flow would certainly be tied back to the web request, hence the framework would actually subscribe. 

If this operation was invoked from the service layer, it would be the service’s job to subscribe or connect to the proper stimulant that does that. 

The most common scenario which doesn’t have such direct responsibility is when you are pre-loading data for a sample app or for some form of test. 

When pre-loading data it’s highly recommend to NOT BLOCK. @mp911de can better describe the details under the hood involving startup. 

When building a test case, if you happen to be using Reactor’s StepVerifier, then THAT tool will subscribe. 

It’s a little strange when you get started with reactive streams, but it’s best if r2dbc does NOT subscribe. Instead, delay subscription until you find the responsible party that actually wants the data and make them subscribe.

**Comment by gregturn** [comment]
Remembering to subscribe is actually a common gotcha for all RS programming. In my latest book, written 100% in Reactor, I repeatedly emphasized the need to subscribe. 

It’s a paradigm that deviates from Java 8 Streams in that often you apply the collect API because often you are the consumer. 

But in RS, it’s actually encouraged to delay subscribing as late as possible for multiple reasons. One being that what you are writing is actually a “recipe” and that multiple subscriptions actually result in multiple executions. Whereas Java 8 streams are the exact opposite. 

So in a sense every RS “recipe” you craft is meant to be composable amidst other flows thus something to not subscribe to until the application has enough context. This usually manifests in someone making a web call or whatever.

**Comment by aguibert** [comment]
What you have described makes sense and I agree with it, but my argument is whether or not DB write operations should be considered in the same category as other RS operations in the first place and therefore require a subscriber.

With read operations it makes sense -- you publish some SQL statements to the DB, then you subscribe to the results. If you don't subscribe to the results, then why make the DB go through the work of fetching data that will never be read? This makes sense to me.

With write operations however, we publish some SQL statements to the DB, and expect the data to be written. The only result we _might_ care about is the row update count. In JDBC an update returns the row update count or 0, but I rarely use this value for anything. I would guess that most applications spin off write operations and disregard any non-exceptional results. If we think this is the case, then it seems R2DBC should be conscious of this and provide an API that accommodates this usage pattern. If we don't think this is the case, then the API is probably fine how it is.

**Comment by gregturn** [comment]
Just to be clear, nothing happens until you subscribe. No retrievals. No writes. Basically, no resource consumption of any kind. 

And we certainly appreciate your inputs on this endeavor.

**Comment by mp911de** [comment]
> Typically don't care about any sort of feedback (unless an exception has been thrown).

This isn't true. Writes populate in a lot of cases an Id field or are used for conditional writes as in optimistic locking.

> I'm still trying to wrap my head around reactive stream stuff (its a pretty radical mind shift)
Deferred execution, responsibility changes in flow control (i.e. no more loops in user code), error handling cause a steep learning curve. We're happy to improve things on our side.

> What you have described makes sense and I agree with it, but my argument is whether or not DB write operations should be considered in the same category as other RS operations in the first place and therefore require a subscriber.

Deferred execution is a primitive of Reactive Streams which makes it an essential part of the programming model. So basically what @gregturn said means: There's no difference in type of operation as all types require subscription. IDE's such as IntelliJ provide good support in hinting for `Publisher`'s that do get subscribed to.

On a general level, you should not `subscribe()` in your application code but rather pass on `Publisher`'s to your runtime container. A plain `subscribe()` ignores completion, failures and potential synchronization.

**Comment by aguibert** [comment]
> Just to be clear, nothing happens until you subscribe. No retrievals. No writes. Basically, no resource consumption of any kind.

Yep, while this can be really powerful in some cases, it's also unfortunately a point of confusion for newcomers to R2DBC like myself.

> This isn't true. Writes populate in a lot of cases an Id field or are used for conditional writes as in optimistic locking.

Good point! Given that, I'm in agreement now that `Handle.execute()` is best suited for returning a `Flux`.

> IDE's such as IntelliJ provide good support in hinting for Publisher's that do get subscribed to.

Cool, I didn't know about this (I use Eclipse).

Thanks for the discussion Greg and Mark. I'll keep thinking of possible ways to make this more intuitive, but in the meantime I'll close out this issue.
