### ISSUE TITLE
R2DBC API: Introduce R2dbcException providing reason, SQLState, and an vendor error code

### ISSUE THREAD

**Issue by mp911de** [r2dbc/r2dbc-client#3]
We should introduce a base exception that allows structured representation of the SQL errors.

**Comment by nebhale** [comment]
Do you have any opinions on whether this should exception should be checked?  I've leaned towards unchecked in the implementation so far rather than adding a `throws` clause to quite a number of methods, but if you think it's more useful for clients to have it checked, I'll make the change.

**Comment by mp911de** [comment]
Let's make it unchecked. Checked exceptions would clutter reactive user code with a lot of error handling code that isn't idiomatic when using functional patterns (Usage of `java.util.function` types).  Also, since exceptions are transported through `Publisher` the number of places that declare exceptions is reduced.
