### ISSUE TITLE
Handle not closed if stream is cancelled

### ISSUE THREAD

**Issue by mostroverkhov** [r2dbc/r2dbc-client#34]
Cancellation of stream created with `R2dbc.withHandle` does not close the `Handle`. This often happens when transforming `Flux` to `Mono` with `Flux.next()`.

Related code snippet on `master` branch
https://github.com/r2dbc/r2dbc-client/blob/07074aa58c33bc2845644fb332004674f8b1b49b/src/main/java/io/r2dbc/client/R2dbc.java#L124

**Comment by mp911de** [comment]
Closing this ticket as we're archiving the repository. See #63.
