### ISSUE TITLE
Support for AS400/DB2

### ISSUE THREAD

**Issue by enricosecondulfo** [r2dbc/r2dbc-client#49]
Is there a possibility of AS400/DB2 support being introduced?
Thank you

**Comment by mp911de** [comment]
We have no knowledge about the DB2 wire protocol. Please reach out to IBM ask them to provide an R2DBC driver. Paging @ebullient and @frowe.

Until then, we cannot provide anything.

**Comment by mp911de** [comment]
IBM announced they are working on a DB2 driver. See https://github.com/IBM/r2dbc-db2 for details. Since this is a pluggable client, there's nothing to do here.
