### ISSUE TITLE
Is there any tutorial or hello world in Spring Boot how use r2dbc-client without Spring-Data

### ISSUE THREAD

**Issue by jimisdrpc** [r2dbc/r2dbc-client#65]
I read "r2dbc-client - client using pure Reactor (i.e. no Spring dependencies)." That fits quite well my problem. We have reactive stack but the data come from blocking database (Oracle). The problem is I see Spring-data for reactive approaches still not in release mode and it causes me issue while moving to production. The problem is that all example I have found from r2dbc-client uses somehow spring-data. Our microservices are bases in Spring world but I can't use any dependeny not delivery yet.

Your example from https://github.com/r2dbc/r2dbc-client seems still depending on Spring Data (PostgresqlConnectionConfiguration). I have nothing against Spring Data but I will be blocked from moving to production if the pom has milestone versions (not definitely release I mean).

**Comment by mp911de** [comment]
This project is no longer maintained. It is on its way being transitioned into the JDBI project. See https://github.com/jdbi/jdbi/pull/1660 for further details.
