### ISSUE TITLE
Ability too access mappable result for executing INSERT statement

### ISSUE THREAD

**Issue by aboodz** [r2dbc/r2dbc-client#66]
#### Is your feature request related to a problem? Please describe
While playing around with r2dbc, I wanted to read the returned results from an INSERT. Given the table `TEST` with columns `ID` and `DESCRIPTION`, when insert a row like this (postgres):
```
handle.execute("INSERT INTO TEST VALUES (1$, $2) RETURNING ID", 1, "bla")
```
I found out that that `execute()` always maps the result into an integer that shows the number of affected rows. I was wishing to be able to read the result of the query. I am aware that not all databases supports `RETURNING` in `INSERT`

#### Describe the solution you'd like
being able to access the result using `.mapResult` or `.map`

#### Describe alternatives you've considered
An alternative way to get the ID is to pre-set from the provided value. Another solution for sequence id is to read them using a select query before executing the `INSERT` statement

**Comment by mp911de** [comment]
Closing this ticket as we're archiving the repository. See #63.
