### ISSUE TITLE
R2DBC API: Provide Row.get(Object identifier)

### ISSUE THREAD

**Issue by mp911de** [r2dbc/r2dbc-client#7]
When reading and mapping data into objects, it's common to have types which differ between the model and its persistent representation. We should have a method to read values and let the driver determine the data type.

Note: Ideally, we have `Row.get(String identifier)` and `Row.get(int index)` methods to tighten up the API contract and resolve ambiguities over the identifier.

**Comment by nebhale** [comment]
I think we should break out the discussion about [identifier types](https://github.com/r2dbc/r2dbc-spi/issues/3) into a separate issue as it's larger than this.

**Comment by nebhale** [comment]
This issue was moved to r2dbc/r2dbc-spi#4
